export { default as Clients } from './clients';
export { default as Contact } from './contact';
export { default as Footer } from './footer';
export { default as Intro } from './intro';
export { default as Navigation } from './navigation';
export { default as Project } from './project';
export { default as Review } from './review';
export { default as Services } from './services';
export { default as Skill } from './skill';
